<?php

use Illuminate\Database\Seeder;

class PodujatiasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('podujatias')->delete();
        $podujatias = array(
            array('id' => 1,'Nazov' => 'Spoznaj Nemecko', 'datum' => '2019-12-13', 'mestos_id' => '2', 'univerzities_id' => '2', 'krajinies_id' => '82','vyzvy_id' => 1,'users_id' => 1, 'pocitadlo' => '5', 'popis' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', 'obrazok' => 'https://old.euba.sk/medzinarodne-vztahy/erasmus/preview-file/erasmus-16815.png'),
            array('id' => 2,'Nazov' => 'Spoznaj Anglicko', 'datum' => '2019-05-26', 'mestos_id' => '1', 'univerzietis_id' => '1', 'krajinies_id' => '230','vyzvy_id' => 2,'users_id' => 2, 'pocitadlo' => '12', 'popis' => 'Feugiat nisl pretium fusce id velit. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Nunc congue nisi vitae suscipit tellus mauris a diam. Nam aliquam sem et tortor consequat id porta nibh venenatis. Sed odio morbi quis commodo odio. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Feugiat pretium nibh ipsum consequat. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. Risus ultricies tristique nulla aliquet enim. Sit amet consectetur adipiscing elit ut aliquam purus sit. Urna molestie at elementum eu facilisis sed. Nec feugiat nisl pretium fusce id velit ut. Ultrices tincidunt arcu non sodales neque. Sem nulla pharetra diam sit.',
                'obrazok' => 'https://old.euba.sk/medzinarodne-vztahy/erasmus/preview-file/erasmus-16815.png'),
            array('id' => 3,'Nazov' => 'Spoznaj Cesko', 'datum' => '2019-10-21', 'mestos_id' => '9', 'univerzietis_id' => '9', 'krajinies_id' => '57','vyzvy_id' => 3,'users_id' => 2, 'pocitadlo' => '2', 'popis' => 'Cursus in hac habitasse platea. Risus nullam eget felis eget nunc lobortis mattis. Id ornare arcu odio ut sem. Tellus mauris a diam maecenas sed. Eget arcu dictum varius duis at. Sed blandit libero volutpat sed cras. Sed euismod nisi porta lorem. Venenatis tellus in metus vulputate eu scelerisque. Risus pretium quam vulputate dignissim suspendisse in est ante in. Nunc sed velit dignissim sodales ut. Sit amet luctus venenatis lectus magna fringilla urna. Cum sociis natoque penatibus et magnis dis parturient montes. Morbi tristique senectus et netus et malesuada fames. Viverra nam libero justo laoreet sit amet cursus sit. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Dolor magna eget est lorem ipsum dolor. Tellus at urna condimentum mattis pellentesque id nibh.', 'obrazok' => 'https://old.euba.sk/medzinarodne-vztahy/erasmus/preview-file/erasmus-16815.png'),
            array('id' => 4,'Nazov' => 'Spoznaj Rakusko', 'datum' => '2019-02-05', 'mestos_id' => '8', 'univerzietis_id' => '8', 'krajinies_id' => '14','vyzvy_id' => 4,'users_id' => 1, 'pocitadlo' => '11', 'popis' => 'Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. In massa tempor nec feugiat nisl pretium. Libero justo laoreet sit amet cursus sit amet dictum sit. Suscipit tellus mauris a diam maecenas. Id aliquet risus feugiat in ante metus dictum. Arcu odio ut sem nulla pharetra diam sit amet nisl. Elit at imperdiet dui accumsan. Libero id faucibus nisl tincidunt eget nullam. Suspendisse interdum consectetur libero id. Vitae justo eget magna fermentum iaculis eu non diam. Enim diam vulputate ut pharetra sit amet aliquam id diam. Sagittis aliquam malesuada bibendum arcu vitae. Erat pellentesque adipiscing commodo elit at imperdiet dui.', 'obrazok' => 'https://old.euba.sk/medzinarodne-vztahy/erasmus/preview-file/erasmus-16815.png'),
            array('id' => 5,'Nazov' => 'Spoznaj Slovinsko', 'datum' => '2019-07-19', 'mestos_id' => '11', 'univerzietis_id' => '11', 'krajinies_id' => '198','vyzvy_id' => 5,'users_id' => 3, 'pocitadlo' => '15', 'popis' => 'Pellentesque habitant morbi tristique senectus et netus. Diam quis enim lobortis scelerisque fermentum dui. Risus feugiat in ante metus dictum at tempor. Posuere lorem ipsum dolor sit amet. Viverra justo nec ultrices dui sapien eget. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Tellus orci ac auctor augue mauris. Odio ut enim blandit volutpat maecenas volutpat. Massa sed elementum tempus egestas sed. Dignissim sodales ut eu sem integer. Sed vulputate mi sit amet mauris. Sit amet est placerat in egestas erat imperdiet sed. Donec massa sapien faucibus et molestie ac feugiat sed. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Massa eget egestas purus viverra accumsan. Urna id volutpat lacus laoreet non.', 'obrazok' => 'https://old.euba.sk/medzinarodne-vztahy/erasmus/preview-file/erasmus-16815.png'),
            array('id' => 6,'Nazov' => 'Spoznaj Rusko', 'datum' => '2019-08-24', 'mestos_id' => '3', 'univerzietis_id' => '3', 'krajinies_id' => '181','vyzvy_id' => 6,'users_id' => 3, 'pocitadlo' => '38', 'popis' => 'Gravida in fermentum et sollicitudin ac orci phasellus egestas tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Porttitor eget dolor morbi non arcu risus quis varius quam. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Cursus metus aliquam eleifend mi in nulla. Sit amet dictum sit amet justo donec. Est lorem ipsum dolor sit amet consectetur. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Dictum fusce ut placerat orci. Interdum velit euismod in pellentesque massa placerat duis. Scelerisque varius morbi enim nunc faucibus a pellentesque. Quisque non tellus orci ac auctor augue mauris augue neque. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Eu non diam phasellus vestibulum lorem sed risus. Ipsum suspendisse ultrices gravida dictum fusce ut. Non odio euismod lacinia at quis risus. At lectus urna duis convallis convallis.', 'obrazok' => 'https://old.euba.sk/medzinarodne-vztahy/erasmus/preview-file/erasmus-16815.png'),
        );
        DB::table('podujatias')->insert($podujatias);
    }
}
